Console.WriteLine("Hello, World!")
// C:\Users\someuser\Desktop>
Random dice = new Random();
int roll = dice.Next(1, 7);
Console.WriteLine(roll);
Random dice = new Random();
int roll = dice.Next(1, 7);
Console.WriteLine(roll);
Random dice = new Random();
Random dice = new();
// int result = Random.Next();
Random dice = new Random();
int roll = dice.Next();
int roll = dice.Next(1, 7);
Console.WriteLine(dice.Next(1, 7));
dice.Next(1, 7);
Random dice = new Random();
int roll = dice.Next(1, 7);
Console.WriteLine(roll);
int number = 7;
string text = "seven";
Console.WriteLine(number);
Console.WriteLine();
Console.WriteLine(text);
Random dice = new Random();
int roll1 = dice.Next();
int roll2 = dice.Next(101);
int roll3 = dice.Next(50, 101);
Console.WriteLine($"First roll: {roll1}");
Console.WriteLine($"Second roll: {roll2}");
Console.WriteLine($"Third roll: {roll3}");
Random dice = new Random();
int roll1 = dice.Next();
int roll2 = dice.Next(101);
int roll3 = dice.Next(50, 101);
Console.WriteLine($"First roll: {roll1}");
Console.WriteLine($"Second roll: {roll2}");
Console.WriteLine($"Third roll: {roll3}");
int firstValue = 500;
int secondValue = 600;
int largerValue;
Console.WriteLine(largerValue);
int firstValue = 500;
int secondValue = 600;
int largerValue;
largerValue = Math.Max(firstValue, secondValue);
Console.WriteLine(largerValue);