Console.WriteLine('b');
// Console.WriteLine('Hello World!');
Console.WriteLine(123);
Console.WriteLine(0.25F);
Console.WriteLine(2.625);
Console.WriteLine(12.39816m);
Console.WriteLine(true);
Console.WriteLine(false);
Console.WriteLine("123");
Console.WriteLine(123);
Console.WriteLine("true");
Console.WriteLine(true);
string firstName;
char userOption;
int gameScore;
decimal particlesPerMillion;
bool processedCustomer;
string firstName;
firstName = "Bob";
// string firstName;
// "Bob" = firstName;
// int firstName;
// firstName = "Bob";
string firstName;
firstName = "Bob";
Console.WriteLine(firstName);
string firstName;
firstName = "Bob";
Console.WriteLine(firstName);
firstName = "Liem";
Console.WriteLine(firstName);
firstName = "Isabella";
Console.WriteLine(firstName);
firstName = "Yasmin";
Console.WriteLine(firstName);
// string firstName;
// Console.WriteLine(firstName);
string firstName = "Bob";
Console.WriteLine(firstName);
var message = "Hello world!";
var message = "Hello world!";
// var message = "Hello World!";
// message = 10.703m;
// var message;
string name = "Bob";
int messages = 3;
decimal temperature = 34.4m;
Console.Write("Hello, ");
Console.Write(name);
Console.Write("! You have ");
Console.Write(messages);
Console.Write(" messages in your inbox. The temperature is ");
Console.Write(temperature);
Console.Write(" celsius.");