Console.WriteLine("Hello World!");
// console.WriteLine("Hello World!");
// Console.WriteLine('Hello World!');
// Console.WriteLine("Hello World!");
Console.Write("Congratulations!");
Console.Write(" ");
Console.Write("You wrote your first lines of code.");
Console.WriteLine("Congratulations!");
Console.Write("You wrote your first lines of code.");
Console.WriteLine("Hello World!");
Console.WriteLine("This is the first line.");
Console.Write("This is ");
Console.Write("the second ");
Console.Write("line.");